name: Build and push to registry

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to AppVenture registry
        uses: docker/login-action@v3
        with:
          registry: registry.nush.app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.nush.app/turtlethread-docs:latest
